### PR TITLE
fix: honor environment variables and cwd unconditionally for SpawnCommand

### LINKED ISSUE #6845: SwitchToWorkspace does not pass through environment variables set in SpawnCommand
### What Operating System(s) are you seeing this problem on?

macOS

### Which Wayland compositor or X11 Window manager(s) are you using?

_No response_

### WezTerm version

20250320-072107-a8735851

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When passing a `SpawnCommand` to the `SwitchToWorkspace` function, the `set_environment_variables` field is ignored.

### To Reproduce

1. Use the configuration below (from https://wezterm.org/config/lua/keyassignment/InputSelector.html), where the `set_environment_variables` has been set.
2. Switch to a workspace using Ctrl-Shift-S.
3. `echo $TEST` prints nothing.

### Configuration

```
local wezterm = require 'wezterm'
local act = wezterm.action
local config = wezterm.config_builder()

config.keys = {
  {
    key = 'S',
    mods = 'CTRL|SHIFT',
    action = wezterm.action_callback(function(window, pane)
      -- Here you can dynamically construct a longer list if needed

      local home = wezterm.home_dir
      local workspaces = {
        { id = home, label = 'Home' },
        { id = home .. '/work', label = 'Work' },
        { id = home .. '/personal', label = 'Personal' },
        { id = home .. '/.config', label = 'Config' },
      }

      window:perform_action(
        act.InputSelector {
          action = wezterm.action_callback(
            function(inner_window, inner_pane, id, label)
              if not id and not label then
                wezterm.log_info 'cancelled'
              else
                wezterm.log_info('id = ' .. id)
                wezterm.log_info('label = ' .. label)
                inner_window:perform_action(
                  act.SwitchToWorkspace {
                    name = label,
                    spawn = {
                      label = 'Workspace: ' .. label,
                      cwd = id,
                      set_environment_variables = { TEST = "OK" },
                    },
                  },
                  inner_pane
                )
              end
            end
          ),
          title = 'Choose Workspace',
          choices = workspaces,
          fuzzy = true,
          fuzzy_description = 'Fuzzy find and/or make a workspace',
        },
        pane
      )
    end),
  },
}

return config
```

### Expected Behavior

`echo $TEST` shall return `OK`.

### Logs

_No response_

### Anything else?

- Setting `args` to `{ '/bin/zsh' }' makes it work.
- Setting `default_prog` to `/bin/zsh` does not solve the issue.

### PR DESCRIPTION
**Pull request by vincentbesanceney**
The SpawnCommand specifies information about a new command to be spawned. If the args field is omitted, the default program for the target domain is spawned. However, this also causes other fields like environment variables and cwd to be wiped out.

The command builder now behaves consistently for all fields, whether the args field is set or omitted.

Fixes #6845

### CODE REVIEW

File: wezterm-gui/src/spawn.rs [hunk 1]
```diff
@@ -68,17 +68,19 @@ pub async fn spawn_command_internal(
...
+        };
         for (k, v) in spawn.set_environment_variables.iter() {
             builder.env(k, v);
         }
         if let Some(cwd) = spawn.cwd {
             builder.cwd(cwd);
         }
         Some(builder)
-    } else {
-        None
```
Comment (wez) [inline wezterm-gui/src/spawn.rs:81]: there's some nuance to this; some domains (eg: serial) will refuse to spawn with anything other than `None` because they cannot build any kind of command.

Could you make another pass at this to ensure that we end up with `None` if none of the spawn-provided fields are set?

Thanks!

Comment (vincentbesanceney) [reply wezterm-gui/src/spawn.rs:81]: Oh ok, I didn't know about serial domains. Here you go. 😊

File: wezterm-gui/src/spawn.rs [hunk 2]
```diff
@@ -68,17 +68,26 @@ pub async fn spawn_command_internal(
...
-            builder.env(k, v);
-        }
-        if let Some(cwd) = spawn.cwd {
-            builder.cwd(cwd);
+    let cmd_builder = match (
+        spawn.args.as_ref(),
+        spawn.cwd.as_ref(),
+        !spawn.set_environment_variables.is_empty(),
+    ) {
+        (None, None, false) => None,
```
Comment (wez) [inline wezterm-gui/src/spawn.rs:76]: Negative logic can be harder to grok, let's flip this around so that it is a bit easier to follow!

```suggestion
        spawn.set_environment_variables.is_empty(),
    ) {
        (None, None, true) => None,
```

**Comment by wez** [comment]
Thank you!
